name: sd

on:
push:
branches:
'main'

jobs:
docker:
runs-on: ubuntu-latest
steps:
-
name: Checkout
uses: actions/checkout@v2
-
name: Log in to YC
uses: docker/login-action@v1
with:
registry: cr.yandex
username: dumb1user
password: AQAAAABZKtJoAATuwfC9OPImb0QEoLie30Ws8oU
-
name: Build, tag, and push image to Yandex Cloud Container Registry
run: |
docker build -t cr.yandex/b1g11l24p26u7quk5s57/ubuntu:latest .
docker push cr.yandex/b1g11l24p26u7quk5s57/ubuntu:latest
